folder_path = os.path.join(subtitle_path, 'Suits')
# deleted_file = rename_Suits(folder_path)
# folder_path = os.path.join(subtitle_path, 'Game of Thrones')
# rename_Game_of_Thrones(folder_path)
# folder_path = os.path.join(subtitle_path, 'Sherlock')
# rename_Sherlock(folder_path)